In [17]:
import pandas as pd
import numpy as np
import seaborn as sns

In [18]:
df=sns.load_dataset("penguins")
df.shape

(344, 7)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [20]:
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [21]:
df.isnull()

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0      False   False           False          False              False   
1      False   False           False          False              False   
2      False   False           False          False              False   
3      False   False            True           True               True   
4      False   False           False          False              False   
..       ...     ...             ...            ...                ...   
339    False   False            True           True               True   
340    False   False           False          False              False   
341    False   False           False          False              False   
342    False   False           False          False              False   
343    False   False           False          False              False   

     body_mass_g    sex  
0          False  False  
1          False  False  
2          False  False  
3           True   True  
4          False  False  
..           ...    ...  
339         True   True  
340        False  False  
341        False  False  
342        False  False  
343        False  False  

[344 rows x 7 columns]

In [22]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [23]:
df.dropna()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
4    Adelie  Torgersen            36.7           19.3              193.0   
5    Adelie  Torgersen            39.3           20.6              190.0   
..      ...        ...             ...            ...                ...   
338  Gentoo     Biscoe            47.2           13.7              214.0   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
4         3450.0  Female  
5         3650.0    Male  
..           ...     ...  
338       4925.0  Female  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[333 rows x 7 columns]

In [24]:
df.dropna(inplace=True)

In [25]:
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [26]:
df.sex.unique()

array(['Male', 'Female'], dtype=object)

In [27]:
df['sex']

0        Male
1      Female
2      Female
4      Female
5        Male
        ...  
338    Female
340    Female
341      Male
342    Female
343      Male
Name: sex, Length: 333, dtype: object

In [28]:
df['sex']=df['sex'].replace({"Male":1,"Female":0})

In [29]:
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
4    Adelie  Torgersen            36.7           19.3              193.0   
5    Adelie  Torgersen            39.3           20.6              190.0   
..      ...        ...             ...            ...                ...   
338  Gentoo     Biscoe            47.2           13.7              214.0   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g  sex  
0         3750.0    1  
1         3800.0    0  
2         3250.0    0  
4         3450.0    0  
5         3650.0    1  
..           ...  ...  
338       4925.0    0  
340       4850.0    0  
341       5750.0    1  
342       5200.0    0  
343       5400.0    1  

[333 rows x 7 columns]

In [30]:
df['sex']

0      1
1      0
2      0
4      0
5      1
      ..
338    0
340    0
341    1
342    0
343    1
Name: sex, Length: 333, dtype: int64

In [18]:
df.island.unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [24]:
pd.get_dummies(df['island']).head()

Biscoe  Dream  Torgersen
0       0      0          1
1       0      0          1
2       0      0          1
4       0      0          1
5       0      0          1

In [25]:
island=pd.get_dummies(df['island'],drop_first = True)
island.head()

Dream  Torgersen
0      0          1
1      0          1
2      0          1
4      0          1
5      0          1

In [26]:
new_data=pd.concat([df,island],axis=1)

In [27]:
new_data.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g  sex  Dream  Torgersen  
0       3750.0    1      0          1  
1       3800.0    0      0          1  
2       3250.0    0      0          1  
4       3450.0    0      0          1  
5       3650.0    1      0          1

In [28]:
new_data.drop(['island'],axis=1,inplace= True)

In [29]:
new_data.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  sex  \
0  Adelie            39.1           18.7              181.0       3750.0    1   
1  Adelie            39.5           17.4              186.0       3800.0    0   
2  Adelie            40.3           18.0              195.0       3250.0    0   
4  Adelie            36.7           19.3              193.0       3450.0    0   
5  Adelie            39.3           20.6              190.0       3650.0    1   

   Dream  Torgersen  
0      0          1  
1      0          1  
2      0          1  
4      0          1  
5      0          1

In [31]:
y=new_data.species
y.head()
y.unique()

array(['Adelie', 'Chinstrap', 'Gentoo'], dtype=object)

In [32]:
y=y.replace({'Adelie':0,'Chinstrap':1,'Gentoo':2})
y.head()

0    0
1    0
2    0
4    0
5    0
Name: species, dtype: int64

In [62]:
new_data.head()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  sex  Dream  \
0            39.1           18.7              181.0       3750.0    1      0   
1            39.5           17.4              186.0       3800.0    0      0   
2            40.3           18.0              195.0       3250.0    0      0   
4            36.7           19.3              193.0       3450.0    0      0   
5            39.3           20.6              190.0       3650.0    1      0   

   Torgersen  
0          1  
1          1  
2          1  
4          1  
5          1

In [41]:
new_data

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  sex  \
0              39.1           18.7              181.0       3750.0    1   
1              39.5           17.4              186.0       3800.0    0   
2              40.3           18.0              195.0       3250.0    0   
4              36.7           19.3              193.0       3450.0    0   
5              39.3           20.6              190.0       3650.0    1   
..              ...            ...                ...          ...  ...   
338            47.2           13.7              214.0       4925.0    0   
340            46.8           14.3              215.0       4850.0    0   
341            50.4           15.7              222.0       5750.0    1   
342            45.2           14.8              212.0       5200.0    0   
343            49.9           16.1              213.0       5400.0    1   

     Dream  Torgersen  
0        0          1  
1        0          1  
2        0          1  
4        0          1  
5        0          1  
..     ...        ...  
338      0          0  
340      0          0  
341      0          0  
342      0          0  
343      0          0  

[333 rows x 7 columns]

In [42]:
x=new_data

In [44]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [46]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=5,criterion='entropy',random_state=0)
classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=5, random_state=0)

In [47]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0,
       2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0,
       2, 2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 2, 1, 0, 2, 2, 1, 2, 1, 0,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2], dtype=int64)

In [49]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,accuracy_score

In [50]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[48  0  0]
 [ 1 15  0]
 [ 1  0 35]]


In [51]:
accuracy_score(y_test,y_pred)

0.98

In [52]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        48
           1       1.00      0.94      0.97        16
           2       1.00      0.97      0.99        36

    accuracy                           0.98       100
   macro avg       0.99      0.97      0.98       100
weighted avg       0.98      0.98      0.98       100



In [58]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=8,criterion='gini',random_state=0)
classifier.fit(x_train,y_train)

RandomForestClassifier(n_estimators=8, random_state=0)

In [59]:
y_pred=classifier.predict(x_test)

In [60]:
accuracy_score(y_test,y_pred)

0.98

In [61]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        48
           1       1.00      0.88      0.93        16
           2       1.00      1.00      1.00        36

    accuracy                           0.98       100
   macro avg       0.99      0.96      0.97       100
weighted avg       0.98      0.98      0.98       100

